# Generated by Django 4.1.3 on 2022-12-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tag_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
