# Generated by Django 4.1.3 on 2022-12-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tag_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
