# Generated by Django 4.1.3 on 2023-01-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tag_id',
            new_name='uid',
        ),
    ]
