# Generated by Django 4.1.3 on 2023-01-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_tag_id_customuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prezime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
