# Generated by Django 4.1.3 on 2023-01-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_ime_customuser_prezime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ime',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prezime',
        ),
    ]
