# Generated by Django 4.1.3 on 2023-01-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_ime_remove_customuser_prezime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.FloatField(default=10),
        ),
    ]
