# Generated by Django 3.2.16 on 2023-01-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(default=12412, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
