# Generated by Django 3.2.16 on 2023-01-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
