# Generated by Django 4.1.3 on 2022-12-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
