# Generated by Django 4.1.3 on 2022-12-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_rename_post_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='user',
        ),
    ]
